services:
  climacan-dev:
    build:
      context: ..
      dockerfile: docker/base.Dockerfile
    container_name: climacan-dev
    networks:
      - dev_network
    env_file:
      - ../.env
    command: sleep infinity

  climacan-influxdb:
    image: influxdb:1.8
    container_name: climacan-influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./volumes/influxdb/data:/var/lib/influxdb
      - ./volumes/influxdb/db:/var/lib/influxdb/backup
    environment:
      - TZ=Atlantic/Canary
    networks:
      - dev_network
    depends_on:
      - climacan-dev
    restart: unless-stopped

  climacan-grafana:
    image: grafana/grafana
    container_name: climacan-grafana
    ports:
      - "3000:3000"
    networks:
      - dev_network
    environment:
      - TZ=Atlantic/Canary
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_LOGS=/var/log/grafana
    depends_on:
      - climacan-dev
    restart: unless-stopped

networks:
  dev_network:
    driver: bridge
