services:
  # climacan-dev:
  #   build:
  #     context: ..
  #     dockerfile: docker/base.Dockerfile
  #   container_name: climacan-dev
  #   env_file:
  #     - ../.env
  #   command: sleep infinity
  #   networks:
  #     - climacan_network

  climacan-influxdb:
    image: influxdb:1.8
    container_name: climacan-influxdb
    ports:
      - "${INFLUXDB_PORT}:8086"
    volumes:
      - ./volumes/influxdb/data:/var/lib/influxdb
      - ./volumes/influxdb/db:/var/lib/influxdb/backup
    environment:
      - TZ=Atlantic/Canary
    # depends_on:
    #   - climacan-dev
    restart: unless-stopped
    networks:
      - climacan_network

  climacan-grafana:
    image: grafana/grafana
    container_name: climacan-grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - ./volumes/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./volumes/grafana/provisioning:/etc/grafana/provisioning
      - ./volumes/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - TZ=Atlantic/Canary
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GRAFANA_PORT=${GRAFANA_PORT}
      - INFLUXDB_PORT=${INFLUXDB_PORT}
    # depends_on:
    #   - climacan-dev
    restart: unless-stopped
    networks:
      - climacan_network

# Definición de red personalizada
networks:
  climacan_network:
    driver: bridge
